<?php

namespace App\Console\Commands;

use App\Services\TelegramBotService;
use App\Services\WkhtmltopdfPdfService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

class TelegramPdfTestCommand extends Command
{
    /**
     * Examples:
     * php artisan telegram:pdf-test --chat=-1001234567890 --caption="Test PDF"
     */
    protected $signature = 'telegram:pdf-test
        {--chat= : Telegram chat_id (group/supergroup/user/channel)}
        {--caption= : Optional caption for Telegram document}';

    protected $description = 'Generate a small PDF via wkhtmltopdf and send it to Telegram (tests wkhtmltopdf + Telegram together)';

    public function handle(WkhtmltopdfPdfService $pdfService, TelegramBotService $telegram): int
    {
        $chatId = trim((string) $this->option('chat'));
        $caption = $this->option('caption');

        if ($chatId === '') {
            $this->error('Usage: php artisan telegram:pdf-test --chat=-100xxxxxxxxxx --caption="Optional caption"');
            return 1;
        }

        $tmpDir = storage_path('app/temp');
        if (! File::exists($tmpDir)) {
            File::makeDirectory($tmpDir, 0755, true);
        }

        $htmlPath = $tmpDir . DIRECTORY_SEPARATOR . 'telegram_pdf_test.html';
        $pdfPath = $tmpDir . DIRECTORY_SEPARATOR . 'telegram_pdf_test.pdf';

        $html = '<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Telegram PDF Test</title>
  <style>
    body { font-family: sans-serif; font-size: 14px; }
    .muted { color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <h2>Telegram PDF Test</h2>
  <p>This PDF was generated by wkhtmltopdf on the server and sent to Telegram.</p>
  <p>Khmer sample: សួស្តី (Hello)</p>
  <p class="muted">Generated at: ' . e(now()->toDateTimeString()) . '</p>
</body>
</html>';

        try {
            File::put($htmlPath, $html);

            if (! $pdfService->isEnabled()) {
                $this->error('wkhtmltopdf is disabled (WKHTMLTOPDF_ENABLED=false).');
                return 1;
            }

            $binary = $pdfService->resolveBinaryPath();
            if (! is_file($binary) || ! is_executable($binary)) {
                $this->error("wkhtmltopdf binary not executable at: {$binary}");
                return 1;
            }

            $args = [$binary];
            $options = (array) config('pdf.wkhtmltopdf.options', []);
            foreach ($options as $flag => $value) {
                $flag = ltrim((string) $flag, '-');

                // Boolean flags: true => pass just --flag
                if ($value === true) {
                    $args[] = '--' . $flag;
                    continue;
                }
                // false/null => skip
                if ($value === false || $value === null) {
                    continue;
                }

                $args[] = '--' . $flag;
                $args[] = (string) $value;
            }

            $args[] = $htmlPath;
            $args[] = $pdfPath;

            $process = new Process($args);
            $process->setTimeout(60);
            $process->run();

            if (! $process->isSuccessful()) {
                throw new ProcessFailedException($process);
            }

            if (! File::exists($pdfPath) || File::size($pdfPath) === 0) {
                throw new \RuntimeException('wkhtmltopdf generated an empty PDF file.');
            }

            $telegram->sendDocumentToChat($chatId, $pdfPath, $caption ?: 'Test PDF', basename($pdfPath));
            $this->info('Sent PDF.');
            return 0;
        } catch (\Exception $e) {
            Log::error('Telegram PDF test error: ' . $e->getMessage());
            $this->error($e->getMessage());
            return 1;
        } finally {
            if (File::exists($htmlPath)) {
                File::delete($htmlPath);
            }
            if (File::exists($pdfPath)) {
                File::delete($pdfPath);
            }
        }
    }
}

