<?php

return [
    'name' => 'LoanManagement',
    'version' => '1.0.0',
    'module_version' => '1.0.0',
    'db_connection' => 'mysql_loan',
    'loan_database_name' => env('DB_LOAN_DATABASE', 'loan'),
    'customer_api_guard' => 'customer_loan_api',
    'customer_api_provider' => 'loan_customers',
    'customer_api_driver' => env('LOAN_CUSTOMER_API_DRIVER', 'auto'),
    'loan_web_guard' => 'loan_web',
    'loan_api_guard' => 'loan_api',
    'loan_user_provider' => 'loan_users',
    'chat_realtime_driver' => env('LOAN_CHAT_REALTIME_DRIVER', 'none'),
    'chat_polling_seconds' => (int) env('LOAN_CHAT_POLLING_INTERVAL', env('LOAN_CHAT_POLLING_SECONDS', 5)),
    'chat' => [
        'broadcasting_enabled' => (bool) env('LOAN_CHAT_BROADCASTING_ENABLED', false),
        'polling_interval_seconds' => (int) env('LOAN_CHAT_POLLING_INTERVAL', 5),
    ],
    'telegram' => [
        'bot_token' => env('LOAN_CHAT_TELEGRAM_BOT_TOKEN', ''),
        'bot_username' => env('LOAN_CHAT_TELEGRAM_BOT_USERNAME', ''),
        'webhook_secret' => env('LOAN_CHAT_TELEGRAM_WEBHOOK_SECRET', ''),
        'link_ttl_minutes' => (int) env('LOAN_CHAT_TELEGRAM_LINK_TTL_MINUTES', 15),
    ],
    'allow_without_pos_stock' => true,
    'google_vision' => [
        'api_key' => env('GOOGLE_CLOUD_VISION_API_KEY', env('GOOGLE_VISION_API_KEY')),
        'endpoint' => env('GOOGLE_CLOUD_VISION_ENDPOINT', 'https://vision.googleapis.com/v1/images:annotate'),
        'timeout' => (int) env('GOOGLE_CLOUD_VISION_TIMEOUT', 30),
    ],
    'openai' => [
        'api_key' => env('OPENAI_API_KEY'),
        'organization' => env('OPENAI_ORGANIZATION'),
        'timeout' => (int) env('OPENAI_TIMEOUT', 45),
        'id_card_model' => env('OPENAI_ID_CARD_MODEL', 'gpt-4.1-mini'),
        'product_photo_model' => env('OPENAI_PRODUCT_PHOTO_MODEL', env('OPENAI_ID_CARD_MODEL', 'gpt-4.1-mini')),
    ],
    'cambodia_address' => [
        'endpoint' => env('CAMBODIA_ADDRESS_API_URL', 'https://data.mef.gov.kh/api/v1/public-datasets/pd_68e370856a965e00074a5e7b/json'),
        'page_size' => (int) env('CAMBODIA_ADDRESS_PAGE_SIZE', 200),
        'pages_per_request' => (int) env('CAMBODIA_ADDRESS_PAGES_PER_REQUEST', 25),
        'timeout' => (int) env('CAMBODIA_ADDRESS_TIMEOUT', 30),
        'verify_ssl' => (bool) env('CAMBODIA_ADDRESS_VERIFY_SSL', true),
        'retry_after_seconds' => (int) env('CAMBODIA_ADDRESS_RETRY_AFTER_SECONDS', 10),
        'cache_days' => (int) env('CAMBODIA_ADDRESS_CACHE_DAYS', 7),
    ],
    'tesseract' => [
        'path' => env('TESSERACT_PATH'),
    ],
    'menu_order' => 38,
    'permissions' => [
        'loan_management.dashboard.view',
        'loan_management.customers.view',
        'loan_management.customers.create',
        'loan_management.customers.edit',
        'loan_management.customers.delete',
        'loan_management.guarantors.view',
        'loan_management.blacklist.view',
        'loan_management.loans.view',
        'loan_management.loans.create',
        'loan_management.loans.edit',
        'loan_management.loans.approve',
        'loan_management.loans.reject',
        'loan_management.schedules.view',
        'loan_management.monthly_payments.view',
        'loan_management.overdue.view',
        'loan_management.payments.view',
        'loan_management.payments.create',
        'loan_management.payment_history.view',
        'loan_management.collection_visits.view',
        'loan_management.gps.view',
        'loan_management.chat.view',
        'loan_management.chat.reply',
        'loan_management.chat.assign',
        'loan_management.chat.transfer',
        'loan_management.chat.close',
        'loan_management.chat.admin',
        'loan_management.aba.view',
        'loan_management.reports.view',
        'loan_management.import.view',
        'loan_management.export.view',
        'loan_management.settings.view',

        'loan_management.view',
        'loan_management.create',
        'loan_management.edit',
        'loan_management.delete',
        'loan_management.approve',
        'loan_management.payment',
        'loan_management.report',
        'loan_management.customers.view',
        'loan_management.customers.create',
        'loan_management.chat.view',
        'loan_management.chat.reply',
        'loan_management.customer_gps.manage',
        'loan_management.setting',

        'loan_management.create_from_sell',
        'loan_management.chat.assign',
        'loan_management.chat.transfer',
        'loan_management.chat.close',
        'loan_management.chat.delete',
        'loan_management.chat.admin',
        'loan_management.collection.view',
        'loan_management.collection.assign',
        'loan_management.collection.recovery',
        'loan_management.collection.legal',
        'loan_management.collection.repossess',
        'loan_management.collection.writeoff',
    ],
];
