<?php

return [
    'name' => 'LoanManagement',
    'version' => '1.0.0',
    'db_connection' => 'mysql_loan',
    'loan_database_name' => env('DB_LOAN_DATABASE', 'loan_management'),
    'loan_web_guard' => 'loan_web',
    'loan_api_guard' => 'loan_api',
    'loan_user_provider' => 'loan_users',
    'chat_realtime_driver' => env('LOAN_CHAT_REALTIME_DRIVER', 'reverb'),
    'chat_polling_seconds' => (int) env('LOAN_CHAT_POLLING_SECONDS', 5),
    'allow_without_pos_stock' => true,
    'menu_order' => 38,
    'permissions' => [
        'loan_management.view',
        'loan_management.create',
        'loan_management.edit',
        'loan_management.delete',
        'loan_management.approve',
        'loan_management.payment',
        'loan_management.report',
        'loan_management.setting',
        'loan_management.sell_list',
        'loan_management.sell_view',
        'loan_management.sell_convert',
        'loan_management.create_from_sell',
        'loan_management.customer_gps.manage',
        'loan_management.chat.view',
        'loan_management.chat.reply',
        'loan_management.chat.assign',
        'loan_management.chat.close',
        'loan_management.chat.admin',
    ],
];
