<?php

return [
    'name' => 'LoanManagement',
    'version' => '1.0.0',
    'db_connection' => 'mysql_loan',
    'loan_database_name' => env('DB_LOAN_DATABASE', 'loan'),
    'customer_api_guard' => 'customer_loan_api',
    'customer_api_provider' => 'loan_customers',
    'customer_api_driver' => env('LOAN_CUSTOMER_API_DRIVER', 'auto'),
    'loan_web_guard' => 'loan_web',
    'loan_api_guard' => 'loan_api',
    'loan_user_provider' => 'loan_users',
    'chat_realtime_driver' => env('LOAN_CHAT_REALTIME_DRIVER', 'none'),
    'chat_polling_seconds' => (int) env('LOAN_CHAT_POLLING_INTERVAL', env('LOAN_CHAT_POLLING_SECONDS', 5)),
    'chat' => [
        'broadcasting_enabled' => (bool) env('LOAN_CHAT_BROADCASTING_ENABLED', false),
        'polling_interval_seconds' => (int) env('LOAN_CHAT_POLLING_INTERVAL', 5),
    ],
    'allow_without_pos_stock' => true,
    'menu_order' => 38,
    'permissions' => [
        'loan_management.dashboard.view',
        'loan_management.customers.view',
        'loan_management.customers.create',
        'loan_management.customers.edit',
        'loan_management.customers.delete',
        'loan_management.guarantors.view',
        'loan_management.blacklist.view',
        'loan_management.loans.view',
        'loan_management.loans.create',
        'loan_management.loans.edit',
        'loan_management.loans.approve',
        'loan_management.loans.reject',
        'loan_management.schedules.view',
        'loan_management.monthly_payments.view',
        'loan_management.overdue.view',
        'loan_management.payments.view',
        'loan_management.payments.create',
        'loan_management.payment_history.view',
        'loan_management.collection_visits.view',
        'loan_management.gps.view',
        'loan_management.chat.view',
        'loan_management.chat.reply',
        'loan_management.chat.assign',
        'loan_management.chat.transfer',
        'loan_management.chat.close',
        'loan_management.chat.admin',
        'loan_management.aba.view',
        'loan_management.reports.view',
        'loan_management.import.view',
        'loan_management.export.view',
        'loan_management.settings.view',

        'loan_management.view',
        'loan_management.create',
        'loan_management.edit',
        'loan_management.delete',
        'loan_management.approve',
        'loan_management.payment',
        'loan_management.report',
        'loan_management.customers.view',
        'loan_management.customers.create',
        'loan_management.chat.view',
        'loan_management.chat.reply',
        'loan_management.customer_gps.manage',
        'loan_management.setting',
        'loan_management.sell_list',
        'loan_management.sell_view',
        'loan_management.sell_convert',
        'loan_management.create_from_sell',
        'loan_management.chat.assign',
        'loan_management.chat.transfer',
        'loan_management.chat.close',
        'loan_management.chat.delete',
        'loan_management.chat.admin',
        'loan_management.collection.view',
        'loan_management.collection.assign',
        'loan_management.collection.recovery',
        'loan_management.collection.legal',
        'loan_management.collection.repossess',
        'loan_management.collection.writeoff',
    ],
];
