<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Telegram PDF Test</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 14px;
            line-height: 1.5;
        }

        .muted {
            color: #666;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <h2>Telegram PDF Test</h2>
    <p>This PDF was generated by the app PDF service and sent to Telegram.</p>
    <p>Khmer sample: &#x179F;&#x17BD;&#x179F;&#x17D2;&#x178F;&#x17B8;</p>
    <p class="muted">Generated at: {{ $generated_at }}</p>
</body>
</html>
